package com.valor.commerce;

enum PaymentStatus { PENDING, PROCESSING, SUCCEEDED, FAILED, CANCELLED, REFUNDED, PARTIALLY_REFUNDED }
enum PaymentPurpose { SERVICE_REQUEST, AMC_RENEWAL, INVOICE, OTHER }
enum InvoiceStatus { DRAFT, ISSUED, PAID, VOID, CANCELLED }
enum RefundStatus { REQUESTED, PROCESSING, SUCCEEDED, FAILED }
enum SupportTicketStatus { SUBMITTED, UNDER_REVIEW, IN_PROGRESS, RESOLVED, CLOSED }
enum SupportTicketPriority { LOW, MEDIUM, HIGH, URGENT }
enum SupportTicketCategory { ACCOUNT, SERVICE_REQUEST, TECHNICAL, BILLING, OTHER }
enum RenewalRequestStatus { REQUESTED, QUOTED, PAYMENT_PENDING, RENEWED, REJECTED, CANCELLED }
enum AssetDocumentOwnerType { BUILDING, LIFT }
