package com.valor;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.http.MediaType;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import java.util.UUID;
import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class Stage1AuthApiTest {
 @Autowired MockMvc mvc; @Autowired ObjectMapper json; @Autowired JdbcTemplate db; @Autowired PasswordEncoder encoder;
 String email(){return "u"+UUID.randomUUID().toString().replace("-","").substring(0,8)+"@example.com";}
 String register(String body)throws Exception{return mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();}
 String login(String path,String identity,String password)throws Exception{return mvc.perform(post(path).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(java.util.Map.of(path.endsWith("customer")?"identity":"email",identity,"password",password)))).andReturn().getResponse().getContentAsString();}
 @Test void flywayV1AndHibernateValidate(){assertEquals(6,db.queryForObject("select count(*) from information_schema.tables where table_name in ('USERS','CUSTOMER_PROFILES','TECHNICIAN_PROFILES','OTP_VERIFICATIONS','REFRESH_TOKENS')",Integer.class));}
 @Test void registrationCreatesCustomerProfileAndRejectsRole()throws Exception{String e=email();register("{\"email\":\"  "+e.toUpperCase()+" \",\"password\":\"Secret123\",\"fullName\":\"A\"}");assertEquals(1,db.queryForObject("select count(*) from users where email=? and role='CUSTOMER'",Integer.class,e));assertEquals(1,db.queryForObject("select count(*) from customer_profiles cp join users u on u.id=cp.user_id where u.email=?",Integer.class,e));mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+email()+"\",\"password\":\"Secret123\",\"fullName\":\"A\",\"role\":\"ADMIN\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.data").isMap());}
 @Test void emailAndPhoneNormalizeAndDuplicate()throws Exception{String e=email();register("{\"email\":\"  "+e.toUpperCase()+" \",\"password\":\"Secret123\",\"fullName\":\"A\"}");assertEquals(1,db.queryForObject("select count(*) from users where email=?",Integer.class,e));mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+e+"\",\"password\":\"Secret123\",\"fullName\":\"A\"}")).andExpect(status().isConflict());String p="+14155552671";register("{\"phone\":\" +1 (415) 555-2671 \",\"fullName\":\"P\"}");assertEquals(1,db.queryForObject("select count(*) from users where phone=?",Integer.class,p));mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"phone\":\""+p+"\",\"fullName\":\"P\"}")).andExpect(status().isConflict());}
 void insert(String email,String role,boolean active,boolean locked)throws Exception{db.update("insert into users(email,password_hash,role,is_active,is_locked,created_at,updated_at) values(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",email,encoder.encode("Secret123"),role,active,locked);}
 @Test void roleSpecificAndWrongRoleLogin()throws Exception{String c=email(),a=email(),t=email();register("{\"email\":\""+c+"\",\"password\":\"Secret123\",\"fullName\":\"C\"}");insert(a,"ADMIN",true,false);insert(t,"TECHNICIAN",true,false);assertThat(login("/api/v1/auth/login/customer",c,"Secret123"),containsString("accessToken"));assertThat(login("/api/v1/auth/login/admin",a,"Secret123"),containsString("accessToken"));assertThat(login("/api/v1/auth/login/technician",t,"Secret123"),containsString("accessToken"));mvc.perform(post("/api/v1/auth/login/customer").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(java.util.Map.of("identity",a,"password","Secret123")))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value("Request could not be processed"));}
 @Test void inactiveAndLockedRejectedAndPasswordHashed()throws Exception{String i=email(),l=email();insert(i,"ADMIN",false,false);insert(l,"ADMIN",true,true);assertThat(login("/api/v1/auth/login/admin",i,"Secret123"),containsString("Request could not be processed"));assertThat(login("/api/v1/auth/login/admin",l,"Secret123"),containsString("Request could not be processed"));String e=email();register("{\"email\":\""+e+"\",\"password\":\"Secret123\",\"fullName\":\"A\"}");String hash=db.queryForObject("select password_hash from users where email=?",String.class,e);assertNotEquals("Secret123",hash);assertTrue(encoder.matches("Secret123",hash));}
 @Test void otpIsHashedExpiryAndAttemptsLimited()throws Exception{String p="+14155552672";String body=mvc.perform(post("/api/v1/auth/otp/send").contentType(MediaType.APPLICATION_JSON).content("{\"phone\":\""+p+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();long requestId=json.readTree(body).at("/data/requestId").asLong();String code=json.readTree(body).at("/data/otp").asText();String hash=db.queryForObject("select otp_hash from otp_verifications order by id desc limit 1",String.class);assertNotEquals(code,hash);assertTrue(encoder.matches(code,hash));for(int i=0;i<3;i++)mvc.perform(post("/api/v1/auth/otp/verify").contentType(MediaType.APPLICATION_JSON).content("{\"phone\":\""+p+"\",\"otp\":\"000000\",\"requestId\":"+requestId+"}"));assertEquals(0,db.queryForObject("select attempts_remaining from otp_verifications order by id desc limit 1",Integer.class));}
 @Test void refreshRotatesAndLogoutRevokesAndMeHidesSecrets()throws Exception{String e=email();String b=register("{\"email\":\""+e+"\",\"password\":\"Secret123\",\"fullName\":\"A\"}");JsonNode d=json.readTree(b).at("/data");String access=d.get("accessToken").asText(),refresh=d.get("refreshToken").asText();String h=db.queryForObject("select token_hash from refresh_tokens order by id desc limit 1",String.class);assertEquals(64,h.length());assertNotEquals(refresh,h);mvc.perform(get("/api/v1/me").header("Authorization","Bearer "+access)).andExpect(status().isOk()).andExpect(jsonPath("$.data.passwordHash").doesNotExist()).andExpect(jsonPath("$.data.tokenHash").doesNotExist());String rb=mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(java.util.Map.of("refreshToken",refresh)))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();String next=json.readTree(rb).at("/data/refreshToken").asText();assertNotEquals(refresh,next);mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(java.util.Map.of("refreshToken",refresh)))).andExpect(status().isBadRequest());mvc.perform(post("/api/v1/auth/logout").header("Authorization","Bearer "+access).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(java.util.Map.of("refreshToken",next)))).andExpect(status().isOk());}
 @Test void protectedAndOldEndpointsUseSafeEnvelope()throws Exception{mvc.perform(get("/api/v1/me")).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false));mvc.perform(get("/api/auth/me")).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false));mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{bad")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").value("Malformed request"));}
 @Test void customerCannotAccessFutureAdminRoutesAnd403IsSafeEnvelope()throws Exception{String e=email();String body=register("{\"email\":\""+e+"\",\"password\":\"Secret123\",\"fullName\":\"C\"}");String token=json.readTree(body).at("/data/accessToken").asText();String response=mvc.perform(get("/api/v1/admin/future").header("Authorization","Bearer "+token)).andExpect(status().isForbidden()).andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").value("Access denied")).andExpect(jsonPath("$.data").value(nullValue())).andReturn().getResponse().getContentAsString();assertFalse(response.contains("password"));assertFalse(response.contains("token"));assertFalse(response.contains("hash"));assertFalse(response.contains("com.valor"));}
}
