CREATE TABLE users (id BIGINT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(254) NULL,phone VARCHAR(20) NULL,password_hash VARCHAR(255) NULL,role VARCHAR(20) NOT NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,is_locked BOOLEAN NOT NULL DEFAULT FALSE,failed_login_attempts INT UNSIGNED NOT NULL DEFAULT 0,locked_until DATETIME(6) NULL,last_login_at DATETIME(6) NULL,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),deleted_at DATETIME(6) NULL,CONSTRAINT uk_users_email UNIQUE(email),CONSTRAINT uk_users_phone UNIQUE(phone),CONSTRAINT ck_users_role CHECK(role IN ('SUPER_ADMIN','ADMIN','CUSTOMER','TECHNICIAN')));
CREATE INDEX idx_users_role_active ON users(role,is_active,is_locked);
CREATE TABLE customer_profiles (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,full_name VARCHAR(160) NOT NULL,alternate_phone VARCHAR(20),company_name VARCHAR(200),address VARCHAR(500),rating DECIMAL(3,2),status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),CONSTRAINT uk_customer_profiles_user UNIQUE(user_id),CONSTRAINT fk_customer_profiles_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT ck_customer_profiles_status CHECK(status IN ('ACTIVE','INACTIVE','SUSPENDED')));
CREATE TABLE technician_profiles (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,employee_id VARCHAR(50),assigned_area VARCHAR(160),specialization VARCHAR(160),availability_status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',rating DECIMAL(3,2),last_working_day DATE,last_active_at DATETIME(6),is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),CONSTRAINT uk_technician_profiles_user UNIQUE(user_id),CONSTRAINT uk_technician_profiles_employee UNIQUE(employee_id),CONSTRAINT fk_technician_profiles_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT ck_technician_profiles_availability CHECK(availability_status IN ('AVAILABLE','BUSY','OFF_DUTY','ON_LEAVE')));
CREATE INDEX idx_technician_profiles_active_availability ON technician_profiles(is_active,availability_status);
CREATE TABLE otp_verifications (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NULL,phone VARCHAR(20) NOT NULL,otp_hash VARCHAR(255) NOT NULL,attempts_remaining SMALLINT UNSIGNED NOT NULL DEFAULT 3,max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 3,expires_at DATETIME(6) NOT NULL,locked_until DATETIME(6),verified_at DATETIME(6),created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),CONSTRAINT fk_otp_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT);
CREATE INDEX idx_otp_phone_created ON otp_verifications(phone,created_at); CREATE INDEX idx_otp_phone_state ON otp_verifications(phone,verified_at,expires_at,locked_until);
CREATE TABLE refresh_tokens (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,token_hash CHAR(64) NOT NULL,expires_at DATETIME(6) NOT NULL,revoked_at DATETIME(6),created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),CONSTRAINT uk_refresh_token_hash UNIQUE(token_hash),CONSTRAINT fk_refresh_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT);
CREATE INDEX idx_refresh_user_expiry ON refresh_tokens(user_id,expires_at,revoked_at);
