alter table technician_applications add column meeting_required boolean not null default false;
alter table technician_applications add column meeting_mode varchar(20);
alter table technician_applications add column meeting_at datetime(6);
alter table technician_applications add column meeting_url varchar(500);
alter table technician_applications add column meeting_phone varchar(40);
alter table technician_applications add column meeting_location varchar(500);
alter table technician_applications add column meeting_latitude decimal(9,6);
alter table technician_applications add column meeting_longitude decimal(9,6);
alter table technician_applications add column meeting_map_url varchar(500);
alter table technician_applications add column meeting_notes varchar(1000);
alter table technician_applications add column meeting_completed_at datetime(6);
alter table technician_applications add column meeting_completed_by_user_id bigint;
alter table technician_applications add column final_approved_at datetime(6);
alter table technician_applications add column final_approved_by_user_id bigint;
alter table technician_applications drop constraint ck_technician_application_status;
alter table technician_applications add constraint ck_technician_application_status check (status in ('DRAFT','OTP_VERIFIED','SUBMITTED','DOCUMENTS_PENDING','UNDER_DOCUMENT_REVIEW','DOCUMENTS_REJECTED','DOCUMENTS_VERIFIED','MEETING_REQUIRED','MEETING_SCHEDULED','MEETING_COMPLETED','APPROVED','REJECTED','SUSPENDED'));
alter table technician_application_documents add column review_status varchar(20) not null default 'PENDING';
alter table technician_application_documents add column reviewer_user_id bigint;
alter table technician_application_documents add column review_reason varchar(1000);
alter table technician_application_documents add column reviewed_at datetime(6);
alter table technician_application_documents add constraint ck_technician_document_review_status check (review_status in ('PENDING','VERIFIED','REJECTED'));
create index idx_technician_application_documents_review on technician_application_documents(application_id,review_status);
