package com.valor.auth;
import org.springframework.context.annotation.*; import org.springframework.stereotype.Component; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.web.*; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.web.filter.OncePerRequestFilter; import jakarta.servlet.*; import jakarta.servlet.http.*; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import com.valor.response.ApiResponse; import java.util.*;
@Configuration class AuthConfig { @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();} @Bean SecurityFilterChain filter(HttpSecurity h,JwtFilter jwt)throws Exception{return h.csrf(c->c.disable()).exceptionHandling(e->e.authenticationEntryPoint((req,res,ex)->{res.setStatus(401);res.setContentType("application/json");res.getWriter().write("{\"success\":false,\"message\":\"Authentication required\",\"data\":null,\"status\":401}");}).accessDeniedHandler((req,res,ex)->{res.setStatus(403);res.setContentType("application/json");res.getWriter().write("{\"success\":false,\"message\":\"Access denied\",\"data\":null,\"status\":403}");})).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/v1/auth/**","/v3/api-docs/**","/swagger-ui/**","/error").permitAll().requestMatchers("/api/v1/admin/**").hasRole("SUPER_ADMIN").anyRequest().authenticated()).addFilterBefore(jwt,UsernamePasswordAuthenticationFilter.class).build();}}
@Component class JwtFilter extends OncePerRequestFilter { final JwtService jwt; final UserRepo users; JwtFilter(JwtService j,UserRepo u){jwt=j;users=u;} protected void doFilterInternal(HttpServletRequest r,HttpServletResponse s,FilterChain c)throws ServletException,java.io.IOException {String h=r.getHeader("Authorization");if(h!=null&&h.startsWith("Bearer "))try{User u=users.findById(jwt.subject(h.substring(7))).orElse(null);if(u!=null&&u.isActive()&&!u.isLocked())SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(u.getId(),null,List.of(()->"ROLE_"+u.getRole())));}catch(Exception ignored){} c.doFilter(r,s);}}
@RestController @RequestMapping("/api/v1") class AuthController {private final AuthService a; AuthController(AuthService x){a=x;} record Reg(String email,String phone,String password,String fullName,String role){} record Login(String identity,String password){} record Otp(String phone,String otp){} record Refresh(String refreshToken){}
 private ApiResponse<?> ok(User u){String[] s=a.session(u);return ApiResponse.success("Authenticated",Map.of("userId",u.getId(),"role",u.getRole(),"accessToken",s[0],"refreshToken",s[1]),200);}
 @PostMapping("/auth/register") ApiResponse<?> reg(@RequestBody Reg r){if(r.role()!=null)throw new IllegalArgumentException("Role cannot be submitted");return ok(a.register(r.email(),r.phone(),r.password(),r.fullName()));}
 @PostMapping("/auth/login/customer") ApiResponse<?> c(@RequestBody Login r){return ok(a.login(r.identity(),r.password(),Set.of(Role.CUSTOMER)));}
 @PostMapping("/auth/login/admin") ApiResponse<?> ad(@RequestBody Login r){return ok(a.login(r.identity(),r.password(),Set.of(Role.ADMIN,Role.SUPER_ADMIN)));}
 @PostMapping("/auth/login/technician") ApiResponse<?> t(@RequestBody Login r){return ok(a.login(r.identity(),r.password(),Set.of(Role.TECHNICIAN)));}
 @PostMapping("/auth/otp/send") ApiResponse<?> send(@RequestBody Otp r){String code=a.sendOtp(r.phone());return ApiResponse.success("Development OTP generated",Map.of("developmentOnly",true,"otp",code),200);}
 @PostMapping("/auth/otp/verify") ApiResponse<?> verify(@RequestBody Otp r){return ok(a.verifyOtp(r.phone(),r.otp()));}
 @PostMapping("/auth/refresh") ApiResponse<?> refresh(@RequestBody Refresh r){String[] s=a.refresh(r.refreshToken());return ApiResponse.success("Token refreshed",Map.of("accessToken",s[0],"refreshToken",s[1]),200);}
 @PostMapping("/auth/logout") ApiResponse<?> logout(@RequestBody Refresh r){a.logout(r.refreshToken());return ApiResponse.success("Logged out",null,200);}
 @GetMapping("/me") ApiResponse<?> me(){var auth=org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication();return ApiResponse.success("Current user",Map.of("userId",auth.getPrincipal()),200);}
}
