package com.valor.auth;
import org.springframework.data.jpa.repository.*; import org.springframework.data.repository.query.Param; import org.springframework.stereotype.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.beans.factory.annotation.Value; import io.jsonwebtoken.*; import io.jsonwebtoken.security.Keys; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.*;
interface UserRepo extends JpaRepository<User,Long>{Optional<User> findByEmail(String e); Optional<User> findByPhone(String p);}
interface CustomerRepo extends JpaRepository<CustomerProfile,Long>{Optional<CustomerProfile> findByUserId(Long id);}
interface TechRepo extends JpaRepository<TechnicianProfile,Long>{Optional<TechnicianProfile> findByUserId(Long id);}
interface OtpRepo extends JpaRepository<OtpVerification,Long>{Optional<OtpVerification> findTopByPhoneAndVerifiedAtIsNullOrderByCreatedAtDesc(String p);}
interface TokenRepo extends JpaRepository<RefreshToken,Long>{Optional<RefreshToken> findByTokenHash(String h);}
@Service class AuthService {
 private final UserRepo users; private final CustomerRepo customers; private final OtpRepo otps; private final TokenRepo tokens; private final PasswordEncoder encoder; private final JwtService jwt;
 AuthService(UserRepo u,CustomerRepo c,OtpRepo o,TokenRepo t,PasswordEncoder e,JwtService j){users=u;customers=c;otps=o;tokens=t;encoder=e;jwt=j;}
 String normEmail(String s){return s==null?null:s.trim().toLowerCase(Locale.ROOT);} String normPhone(String s){if(s==null)return null; String p=s.trim().replaceAll("[\\s\\-()]",""); if(!p.matches("\\+[1-9]\\d{7,14}")) throw new IllegalArgumentException("Invalid phone"); return p;}
 @Transactional User register(String email,String phone,String password,String name){email=normEmail(email);phone=normPhone(phone); if(email==null&&phone==null)throw new IllegalArgumentException("Email or phone required"); if(email!=null&&password==null)throw new IllegalArgumentException("Password required"); if(email!=null&&users.findByEmail(email).isPresent()||phone!=null&&users.findByPhone(phone).isPresent())throw new IllegalArgumentException("Registration unavailable"); User u=new User();u.setEmail(email);u.setPhone(phone);u.setPasswordHash(password==null?null:encoder.encode(password));u.setRole(Role.CUSTOMER);users.save(u);CustomerProfile p=new CustomerProfile();p.setUser(u);p.setFullName(name);customers.save(p);return u;}
 User login(String identity,String password,Set<Role> allowed){String key=identity==null?null:identity.trim().toLowerCase(Locale.ROOT); User u=key!=null&&key.contains("@")?users.findByEmail(key).orElse(null):users.findByPhone(normPhone(identity)).orElse(null); if(u==null||!allowed.contains(u.getRole())||!u.isActive()||u.isLocked()||u.getPasswordHash()==null||!encoder.matches(password,u.getPasswordHash()))throw new IllegalArgumentException("Authentication failed");u.setLastLoginAt(LocalDateTime.now());users.save(u);return u;}
 @Transactional String[] session(User u){String access=jwt.issue(u);String raw=UUID.randomUUID().toString()+UUID.randomUUID().toString();RefreshToken t=new RefreshToken();t.setUser(u);t.setTokenHash(hash(raw));t.setExpiresAt(LocalDateTime.now().plusDays(7));tokens.save(t);return new String[]{access,raw};}
 @Transactional String[] refresh(String raw){RefreshToken t=tokens.findByTokenHash(hash(raw)).orElseThrow(()->new IllegalArgumentException("Invalid refresh token"));if(t.getRevokedAt()!=null||t.getExpiresAt().isBefore(LocalDateTime.now()))throw new IllegalArgumentException("Invalid refresh token");t.setRevokedAt(LocalDateTime.now());tokens.save(t);return session(t.getUser());}
 @Transactional void logout(String raw){tokens.findByTokenHash(hash(raw)).ifPresent(t->{t.setRevokedAt(LocalDateTime.now());tokens.save(t);});}
 @Transactional String sendOtp(String phone){phone=normPhone(phone);String code=String.valueOf(100000+new Random().nextInt(900000));OtpVerification o=new OtpVerification();o.setPhone(phone);o.setOtpHash(encoder.encode(code));o.setExpiresAt(LocalDateTime.now().plusMinutes(5));otps.save(o);return code;}
 @Transactional(noRollbackFor=IllegalArgumentException.class) User verifyOtp(String phone,String code){OtpVerification o=otps.findTopByPhoneAndVerifiedAtIsNullOrderByCreatedAtDesc(normPhone(phone)).orElseThrow(()->new IllegalArgumentException("OTP invalid"));if(o.getExpiresAt().isBefore(LocalDateTime.now())||o.getAttemptsRemaining()<=0)throw new IllegalArgumentException("OTP invalid");if(!encoder.matches(code,o.getOtpHash())){short remaining=(short)(o.getAttemptsRemaining()-1);o.setAttemptsRemaining(remaining);if(remaining<=0)o.setLockedUntil(LocalDateTime.now().plusMinutes(15));otps.save(o);throw new IllegalArgumentException("OTP invalid");}o.setVerifiedAt(LocalDateTime.now());User u=users.findByPhone(normPhone(phone)).orElseGet(()->{User n=new User();n.setPhone(normPhone(phone));n.setRole(Role.CUSTOMER);return users.save(n);});o.setUser(u);otps.save(o);return u;}
 static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
@Component class JwtService {private final javax.crypto.SecretKey key; @Value("${jwt.expiration:86400000}") long exp; JwtService(@Value("${jwt.secret}") String s){if(s==null||s.length()<32)throw new IllegalStateException("JWT_SECRET must be configured");key=Keys.hmacShaKeyFor(s.getBytes(StandardCharsets.UTF_8));} String issue(User u){return Jwts.builder().subject(String.valueOf(u.getId())).claim("role",u.getRole().name()).issuedAt(new Date()).expiration(new Date(System.currentTimeMillis()+exp)).signWith(key).compact();} Long subject(String token){return Long.valueOf(Jwts.parser().verifyWith(key).build().parseSignedClaims(token).getPayload().getSubject());}}
